name: DevTest with Lys Agent

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  devtest-analysis:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: Run Maven Test and Capture Logs
        id: run_tests
        run: |
          set -o pipefail
          mvn clean verify 2>&1 | tee error.log
        continue-on-error: true

      - name: Install jq
        if: steps.run_tests.outcome == 'failure'
        run: |
          sudo apt-get update
          sudo apt-get install -y jq

      - name: Dar permissão ao script
        if: steps.run_tests.outcome == 'failure'
        run: chmod +x ./analisar_log.sh

      - name: Authenticate and Analyze Error with Lys
        if: steps.run_tests.outcome == 'failure'
        env:
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          REALM: ${{ secrets.REALM }}
        run: bash ./analisar_log.sh

      - name: Save Lys response as artifact
        if: steps.run_tests.outcome == 'failure'
        uses: actions/upload-artifact@v4
        with:
          name: lys-analysis
          path: |
            lys_response.json
            resposta_lys.md