name: DevTest with Lys Agent

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  devtest-analysis:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: Run Maven Test and Capture Logs
        id: run_tests
        run: |
          mvn clean verify 2>&1 | tee error.log

      - name: Export error.log as env
        if: failure()
        id: export_log
        run: |
          echo "error_log<<EOF" >> $GITHUB_ENV
          cat error.log >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Analisar log de erro com StackSpot AI (Lys)
        if: failure()
        uses: stackspot-core/stackspot-ai-quick-command@0
        id: lys_analysis
        with:
          quick_command_slug: devtest_lys_analysis
          input_data: |
            { "logs_erro": "${{ env.error_log }}" }
          client_id: ${{ secrets.CLIENT_ID }}
          client_key: ${{ secrets.CLIENT_KEY }}
          realm: ${{ secrets.REALM }}

      - name: Salvar análise da Lys em arquivo
        if: failure()
        run: |
          echo "${{ steps.lys_analysis.outputs.answer }}" > lys_response.txt

      - name: Upload análise da Lys como artefato
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: lys-analysis
          path: lys_response.txt